#!/bin/bash
# ============================================================================
# 🤖 AERIS-10N MAINBOARD AUTOMATED WORKFLOW
# Fully automated - NO MANUAL WORK REQUIRED
# ============================================================================
# This script:
# 1. Adds missing connectors to schematic
# 2. Updates PCB with connector footprints
# 3. Connects nets automatically
# 4. Runs DRC
# 5. Exports Gerbers
# 6. Commits to Git
# ============================================================================

set -e  # Exit on error

echo "============================================================"
echo "🤖 AERIS-10N MAINBOARD AUTOMATED WORKFLOW"
echo "============================================================"

PROJECT_ROOT="/Users/mac/PLFM_RADAR_NEWS"
MAINBOARD_DIR="$PROJECT_ROOT/MainBoard"
SCH_FILE="$MAINBOARD_DIR/RADAR_Main_Board/RADAR_Main_Board_3.kicad_sch"
PCB_FILE="$MAINBOARD_DIR/RADAR_Main_Board/RADAR_Main_Board.kicad_pcb"
OUTPUT_DIR="$MAINBOARD_DIR/RADAR_Main_Board"

# Step 1: Run connector addition script
echo ""
echo "Step 1/6: Adding connectors to schematic..."
python3 "$MAINBOARD_DIR/auto_add_connectors.py"

# Step 2: Copy auto schematic to main
echo ""
echo "Step 2/6: Updating main schematic..."
cp "$OUTPUT_DIR/RADAR_Main_Board_3_auto.kicad_sch" "$SCH_FILE"

# Step 3: Create automated net connections
echo ""
echo "Step 3/6: Creating automated net connections..."
python3 "$MAINBOARD_DIR/auto_connect_nets.py"

# Step 4: Update PCB from schematic
echo ""
echo "Step 4/6: Updating PCB from schematic..."
python3 "$MAINBOARD_DIR/auto_update_pcb.py"

# Step 5: Run DRC
echo ""
echo "Step 5/6: Running Design Rule Check..."
python3 "$MAINBOARD_DIR/auto_run_drc.py"

# Step 6: Export Gerbers
echo ""
echo "Step 6/6: Exporting Gerbers..."
python3 "$MAINBOARD_DIR/auto_export_gerbers.py"

# Git commit
echo ""
echo "============================================================"
echo "📦 COMMITTING TO GITHUB"
echo "============================================================"

cd "$PROJECT_ROOT"
git add MainBoard/
git commit -m "🤖 AUTOMATED: MainBoard connector addition complete

Fully automated workflow completed:
✅ Connectors added (J_PWR_IN, J_TILE_SYNC, J_PA_BIAS)
✅ Nets connected automatically
✅ PCB updated from schematic
✅ DRC passed
✅ Gerbers exported

No manual work required - all steps automated via Python scripts.

Generated by: auto_workflow.sh"

# Push to GitHub
echo ""
echo "🚀 Pushing to GitHub..."
git stash
git pull origin main --rebase
git stash pop
git push origin main

echo ""
echo "============================================================"
echo "✅ WORKFLOW COMPLETE!"
echo "============================================================"
echo ""
echo "📁 Generated files:"
echo "   - Schematic: $OUTPUT_DIR/RADAR_Main_Board_3_auto.kicad_sch"
echo "   - PCB: $OUTPUT_DIR/RADAR_Main_Board_auto.kicad_pcb"
echo "   - Gerbers: $OUTPUT_DIR/Gerber/"
echo "   - Reports: $OUTPUT_DIR/DRC_REPORT.txt"
echo ""
echo "📊 Next steps:"
echo "   1. Review Gerbers: open $OUTPUT_DIR/Gerber/"
echo "   2. Send to manufacturer"
echo "   3. Order components from BOM"
echo ""
echo "============================================================"
